name: dinotis
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  carousel_slider: 4.2.1
  firebase_core: 2.13.0
  firebase_auth: 4.6.1
  flutter_launcher_icons: 0.13.1
  flutter_svg: 2.0.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/svg/
  uses-material-design: true

flutter_launcher_icons: 
  android: launcher_icon
  image_path: assets/images/Logo.png
  web: 
    image_path: assets/images/Logo.png
    background_color: '#hexcode'
    theme_color: '#hexcode'
    generate: true
  windows: 
    image_path: assets/images/Logo.png
    generate: true
    icon_size: 48
  macos: 
    image_path: assets/images/Logo.png
    generate: true
  ios: true
  min_sdk_android: 21

